#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ''
echo 'Inicio do pre-push.'
echo ''
yarn lint-staged
echo ''
echo 'Inicio do test.'
echo ''
yarn test
echo ''
echo 'Fim do test.'
echo ''
echo ''
echo 'Fim do pre-push.'
echo ''
